services:
  laa-means-match-prototype:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PASSWORD=password
      - USE_HTTPS=false
    user: "1001:1001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 40s
