services:
  prototype-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - GOVUK_PROTOTYPE_KIT_USAGE_DATA=false
    command: npm run dev
